### ISSUE TITLE
Platform needed: Centos 6

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-ruby-runtime#12]
Current Centos builds are based on Centos 7 and won't run on Centos 6:

```
ruby: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ruby) ruby: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ruby) ruby: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/cache/sensu/sensu-agent/1c9f0aff8f7f7dfcf07eb75f48c3b7ad6709f2bd68f2287b4bd07979e6fe12c2ab69d1ecf5d4b9b9ed7b96cd4cda5e55c116ea76ce3d9db9ff74538f0ea2317a/lib/libcrypt.so.1)
```

**Comment by rgeniesse** [comment]
Just wanted to throw out there that the current assets built on CentOS 7 have just `centos` in the asset name. Example:

https://github.com/sensu-plugins/sensu-plugins-redis/releases/download/4.2.0/sensu-plugins-redis_4.2.0_centos_linux_amd64.tar.gz

While new releases with say `centos_6` in them instead would work, may want to ensure that the CentOS 7 versions are updated to include 7 in them for users to know.

**Comment by jspaleta** [comment]
okay i did some testing here... definitely need separate centos6 and centos7 runtimes due to glibc changes in libc.so.  
I've got pull requests in flight to start cleaning this up.

**Comment by annaplotkin** [comment]
@jspaleta can we get the in-flight PRs added to this issue?

**Comment by jspaleta** [comment]
0.0.6 release just released includes a Centos6 asset target
