### ISSUE TITLE
Bug Fix: add ldd based scripting to automate system library inclusion in generated assets

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-ruby-runtime#13]
**Problem:**
the ruby-install process installs several dynamically linked C libraries as part of the ruby install. 
Inspecting these shared libraries indicates several system libraries are being linked and we are basically hoping that the running environment will provide them.

Right now we aren't making an effort to include the system libraries in the built asset, but this is going to lead to problems for specific gems that end up required impacted ruby modules. Not all gems...so its hard to predict what will fail.

Currently manifests as missing openssl shared library in the sensu-plugins-http asset.

**Solution:**
use ldd in scripted fashion to determine the full set of system libraries to include in the asset.

**Complication**
Need to do something with regard to providing licensing information for each included library

**Comment by calebhailey** [comment]
Related: https://github.com/calebhailey/sensu-asset-utils/issues/1

**Comment by jspaleta** [comment]
closing  0.0.6 release includes ldd scripting to populate shared libs in the assets
