### ISSUE TITLE
Runtime not working on sensu:sensu container (Alpine 3.8)

### ISSUE THREAD

**Issue by JqckB** [sensu/sensu-ruby-runtime#15]
I found that the Dockerfile in this repository build on alpine:latest, that match 3.9.4 as of today and this ruby runtime build doesn't work with Alpine 3.8 official sensu image.

I only changed to alpine:3.8 and it's working.

Is it expected to have a repository that doesn't match the official sensu docker image ?

**Comment by JqckB** [comment]
My 2 cent : Would it be interesting to have a build based on the sensu image directly ? 

This one can be included with name and version and will be always compatible with the sensu image.

**Comment by jspaleta** [comment]
I'd like to try to understand what the underlying problem here is.   A few questions.

Does your rebuilt ruby-runtime work with existing ruby plugin asset binaries?

What are the error message you are getting prior to making the change?

**Comment by jspaleta** [comment]
I've just released 0.0.6 release that includes an explicit alpine3.8 Dockerfile and associated Docker image and Sensu asset.  Please test to make sure the 0.0.6 solves your issue.

**Comment by JqckB** [comment]
Does your rebuilt ruby-runtime work with existing ruby plugin asset binaries?
No.

What are the error message you are getting prior to making the change?
I've got an error like this 
```
Error relocating /var/lib/sensu/85a221a111fc83563e18dc944f8161c81cb8f882b09939ff359bdd87480ffb8f7bfce0ef3987cb1ae88826dad1903693c9f6d01dd8db8336e4d86e847a2c7c90/bin/ruby: explicit_bzero: symbol not found
```

When building from "alpine:3.8" instead of "alpine:latest", it is working.

On 0.0.6 release, and local build from it, it is working.

**Comment by JqckB** [comment]
It's also working from bonsai binary (0.0.6)

**Comment by jspaleta** [comment]
Okay I'm closing this issue at it appears that 0.0.6 fixes this for you. Please re-open if I'm wrong about that.

**Comment by jspaleta** [comment]
Okay this is really really weird.. I'm going back and checking this and using alpine:3.8 is no longer working for me.

I'm leaving this open and seeing if I can ge another set of eyes

**Comment by JqckB** [comment]
Let me check tomorrow on my setup and I will come back to you here tomorrow
!

**Comment by jspaleta** [comment]
@JqckB   I've written up the steps I'm using in #20 

I swear I had tested all of this before closing the issue, this is really bizarro. Did alpine perhaps re-upload the 3.8 tag with a new image?

**Comment by jspaleta** [comment]
bah they did... 3.8 tag updated 2 days ago.... oh alpine

**Comment by jspaleta** [comment]
we are going to have the same sort of problem if wew tried to base it on the sensu image, because the sensu image if it needs to be rebuilt..will pull in whatever alpine has tagged as 3.8.

So the underlying issue is.. how do we get ruby native extensions to build consistently on alpine.. maybe we are missing a package we need to install or something

**Comment by jspaleta** [comment]
okay i think i have a fix, need to set some configure flags the correct way when building the ruby. Testing now. Probably going to spin up a new runtime release tonight/tomorrow

**Comment by jspaleta** [comment]
Closing for now.
I did a test build using 0.0.8 and 0.0.9 ruby runtime docker images  

built sensu-plugins-http which uses libcurl native extension trhough typhoeus gem.
alpine builds completed and produced assets
