### ISSUE TITLE
Linking error for ZLIB_1.2.9 running Debian builds on Ubuntu 18.04

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-ruby-runtime#32]
When running check-ping.rb from sensu-plugins-network-checks, using the `--report` flag shells out to `mtr`. 

On Ubuntu 18.04 using Debian builds sensu-ruby-runtime 0.10, this combination causes a linking error:

```
mtr: /var/cache/sensu/sensu-agent/a28952fd93fc63db1f8988c7bc40b0ad815eb9f35ef7317d6caf5d77ecfbfd824a9db54184400aa0c81c29b34cb48c7e8c6e3f17891aaf84cafa3c134266a61a/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
```

- [ ] Reproduce on 0.11
- [ ] Fix it

**Comment by jspaleta** [comment]
Okay I was original mistaken this is a problem in the network plugin.   
The shell out to mtr is the underlying problem.  The network plugin asset needs to bundle mtr and the libs it needs.
