### ISSUE TITLE
script not found error

### ISSUE THREAD

**Issue by balajik1992** [sensu/sensu-ruby-runtime#8]
Hi Team,

I created the runtime asset as follows
{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "name": "sensu-ruby-runtime",
    "namespace": "default",
    "labels": {},
    "annotations": {}
  },
  "spec": {
    "url": "$URL",
    "sha512": "$sha512",
    "filters": [
      "entity.system.os == 'linux'",
      "entity.system.arch == 'amd64'"
    ]
  }
}

hello world asset as follows

{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "name": "helloworld-v0.1",
    "namespace": "default",
    "labels": {},
    "annotations": {}
  },
  "spec": {
    "url": "$URL",
    "sha512": "$SHA512",
    "filters": [
      "entity.system.os == 'linux'",
      "entity.system.arch == 'amd64'"
    ]
  }
}

Created check configuration as follows

{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "helloworld",
    "namespace": "default",
    "labels": {},
    "annotations": {}
  },
  "spec": {
    "command": "helloworld.rb",
    "runtime_assets": ["sensu-ruby-runtime", "helloworld-v0.1"],
    "publish": true,
    "interval": 10,
    "subscriptions": ["linux"]
  }
}

Ran sensuctl create -f on all files

Still I am not able to see the check is working
It is giving the error "sh: helloworld.rb: command not found"

Please let me know what I am missing here

**Comment by jspaleta** [comment]
I'd need the url for the helloworld tarball so I could examine it.

Best guess without having more information is you didn't place the helloword.rb  into the "bin/" subdirectory of the tarball.

**Comment by jspaleta** [comment]
Hey!
I'm going to go ahead and close this out as the ticket seems to have gone stale.  
Please feel free to re-open it if you are still having problems and can provide the additional information requested
